apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-adminserver-config
data:
  EXT_ENDPOINT: "http://adminserver.com" 
  AUTH_MODE: "db_auth"
  SELF_REGISTRATION: "true"
  DATABASE_TYPE: "mysql"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_USR: "root"
  MYSQL_PWD: "root123"
  MYSQL_DATABASE: "registry"
  REGISTRY_URL: "http://registry:5000"
  TOKEN_SERVICE_URL: "http://ui/service/token"
  HARBOR_ADMIN_PASSWORD: "Harbor12345"
  PROJECT_CREATION_RESTRICTION: "everyone"
  VERIFY_REMOTE_CERT: "true"
  MAX_JOB_WORKERS: "3"
  UI_SECRET: "FqlQvjkCUcuObAAu"
  JOBSERVICE_SECRET: "Our70VfxrN6uWV4D"
  TOKEN_EXPIRATION: "30"
  CFG_EXPIRATION: "5"
  GODEBUG: "netdns=cgo"
  WITH_NOTARY: "false"
  WITH_CLAIR: "false"
  CLAIR_DB_PASSWORD: "password"
  RESET: "false"
  KEY_PATH: "/secret/key"
  key: "W1BXSwA84cLnvsFP"
