{{- if .Values.nginx.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-{{ .Values.nginx.name }}"
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.nginx.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.nginx.fqdn | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.nginx.name }} 
              servicePort: {{ .Values.nginx.service.port }}
  tls:
    - secretName: {{ .Values.nginx.ingress.tls.secretName | quote }}
      hosts:
        - {{ .Values.nginx.fqdn | quote }}
{{- end }}
