apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }} 
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    name: "{{ .Release.Name }}-{{ .Values.nginx.name }}"
  type: {{ .Values.nginx.service.type }}
  ports:
    - name: portus
      port: {{ .Values.nginx.service.port }}
  {{- if and (eq "NodePort" .Values.nginx.service.type) .Values.nginx.service.nodePort }}
      nodePort: {{ .Values.nginx.service.nodePort }}
  {{- end }}
