apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Values.portus.name }}"
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.portus.password }}
  PORTUS_PASSWORD: {{ .Values.portus.password | b64enc | quote }}
  {{- else }}
  PORTUS_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

  {{- if .Values.portus.secretKeyBase }}
  PORTUS_SECRET_KEY_BASE: {{ .Values.portus.secretKeyBase | b64enc | quote }}
  {{- else }}
  PORTUS_SECRET_KEY_BASE: {{ randAlphaNum 128 | b64enc | quote }}
  {{- end }}

  {{- if eq .Values.mariadb.enabled false }}
  PORTUS_PRODUCTION_PASSWORD: {{ .Values.portus.productionPassword | b64enc | quote }}
  {{- end }}

  key: {{ .Values.portus.key | b64enc | quote }}
  cert: {{ .Values.portus.cert | b64enc | quote }}
