apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.portus.service.name }} 
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    name: {{ template "portus.fullname" . }}
  ports:
    - name: "{{ .Values.portus.service.name }}"
      port: {{ .Values.portus.service.port }} 
