{{- if .Values.registry.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{ .Values.registry.name }}"
  labels:
    storage: "{{ .Release.Name }}-{{ .Values.registry.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.registry.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.registry.persistence.capacity }}
{{- end }}
