apiVersion: v1
kind: ConfigMap
metadata:
  name: portus-registry-config
data:
  REGISTRY_AUTH_TOKEN_REALM: "http://nginx:32123/v2/token"
  REGISTRY_AUTH_TOKEN_SERVICE: "registry:5000"
  REGISTRY_AUTH_TOKEN_ISSUER: "nginx"
  REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: "certificates/portus.crt"
  REGISTRY_NOTIFICATIONS_ENDPOINTS: >
    - name: nginx
      url: http://nginx:32123/v2/webhooks/events
      timeout: 2000ms
      threshold: 5
      backoff: 1s
  config: |
    version: 0.1
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: 0.0.0.0:5000
      debug:
        addr: 0.0.0.0:5001
