apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  ports:
    - name: repo
      port: 30521
      nodePort: 30521
    - name: debug
      port: 5001
  selector:
    name: portus-registry-apps
