apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portus-nginx-deployment
  labels:
    name: portus-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: portus-nginx-apps
  template:
    metadata:
      labels:
        name: portus-nginx-apps
    spec:
      containers:
      - name: portus-nginx-apps
        image: library/nginx:alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx
        - name: certvol
          mountPath: /certificates
          readOnly: true
        ports:
          - containerPort: 443
      volumes:
        - name: certvol
          secret:
            secretName: portus-secrets
            items:
            - key: key
              path: portus.key
            - key: cert
              path: portus.crt
        - name: conf
          configMap:
            name: portus-nginx-config
            items:
            - key: conf
              path: nginx.conf
