apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  ports:
    - name: repo
      port: 5000
      nodePort: 30522
    - name: debug
      port: 5001
  selector:
    name: harbor-registry-apps
