apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: harbor-registry-deployment
  labels:
    name: harbor-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: harbor-registry-apps
  template:
    metadata:
      labels:
        name: harbor-registry-apps
    spec:
      containers:
      - name: harbor-registry-apps
        image: vmware/registry:2.6.2-photon 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        - containerPort: 5001
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry
      volumes:
      - name: config
        configMap:
          name: harbor-registry-config
          items:
          - key: config
            path: config.yml
          - key: cert
            path: root.crt
