apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: harbor-ui-deployment
  labels:
    name: harbor-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: harbor-ui-apps
  template:
    metadata:
      labels:
        name: harbor-ui-apps
    spec:
      containers:
      - name: ui-apps
        image: vmware/harbor-ui:v1.2.0 
        imagePullPolicy: IfNotPresent
        env:
          - name: LOG_LEVEL 
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: LOG_LEVEL 
          - name: CONFIG_PATH 
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: CONFIG_PATH 
          - name: UI_SECRET 
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: UI_SECRET 
          - name: JOBSERVICE_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: JOBSERVICE_SECRET 
          - name: GODEBUG 
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: GODEBUG 
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/ui
      volumes:
      - name: config
        configMap:
          name: harbor-ui-config
          items:
          - key: conf
            path: app.conf
          - key: key
            path: key
          - key: pem 
            path: private_key.pem
