## Default values for Portus Helm Chart.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## Default values for Portus
##
portus:
  replicas: 1

  ## Image configuration.
  ##
  image:
    repository: "opensuse/portus"
    tag: "head"
    pullPolicy: "IfNotPresent"

  ## Service configuration.
  ##
  service:
    port: "3000"

  ## Resource configuration.
  ##
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"

  ## Portus database configuration.
  ##
  productionDatabase: "portus" # name of database
  productionUsername: "portus" # database user

  ## only set productionHost and productionPassword if relying on existing mariadb deployment
  ##
  # productionHost:
  # productionPassword:

  ## Defaults to a random 10-character alphanumeric string if not set
  ##
  # password:

  ## Defaults to a random 128-character alphanumeric string if not set
  ##
  # secretKeyBase:

  ## TLS configuration
  ## the internal host names of the portus, registry and nginx service must be covered by the key/cert in order for TLS to work properly
  ##
  tls:
    enabled: false

    ## must include key if using tls
    ##
    # key: |

    ## must include certificate if using tls
    ##
    # cert: |
 
## Default values for Crono. 
##
crono:
  replicas: 1

  ## image configuration.
  ##
  image:
    repository: "opensuse/portus"
    tag: "head"
    pullPolicy: "IfNotPresent"

  ## Resource configuration.
  ##
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"

## Default values for Docker Registry.
##
registry:
  replicas: 1
  mountPath: "/storage"

  ## persistence configuration.
  ##
  persistence:
    enabled: false # true
    accessMode: "ReadWriteOnce"
    size: "10Gi"

  ## image configuration.
  ##
  image:
    repository: "library/registry"
    tag: "latest"
    pullPolicy: "IfNotPresent"

  ## Service configuration.
  ##
  service:
    port: "5000"
    debugPort: "5001"

  ## Resource configuration.
  ##
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"

## Default values for Nginx.
##
nginx:
  replicas: 1

  ## image configuration.
  ##
  image:
    repository: "library/nginx"
    tag: "alpine"
    pullPolicy: "IfNotPresent"

  ## Service configuration.
  ##
  service:
    ## Set to ClusterIP if using ingress, or NodePort if using minikube 
    ##
    type: "NodePort"

    port: "80"
    nodePort: "32123"

  ## in order to access the docker registry from outside of the cluster
  ## if ingress is enabled set host to the domain you are using
  ## if LoadBalancer is being used set host to the LoadBalancer name
  ## if NodePort is being used set host to the ip address of a cluster node
  ##
  host: "portus-test.us.to"

  ## ingress configuration.
  ##
  ingress:
    enabled: false

    ## Anntations to be added to the web ingress
    ##
    # annotations:
    #   kubernetes.io/ingress.class: "nginx"

    # SHOULD I REMOVE?
    #   kubernetes.io/ingress.allow-http: "false"
    #   ingress.kubernetes.io/ssl-passthrough: "true"

    ## TLS configuration
    ## the ingress host must be covered by the key/cert in order for TLS to work properly
    ##
    # tls:
      # enabled: false

      ## Secrets containing SSL key and cert must be manually created in the namespace
      ##
      # secretName: "portus-tls"

  ## Resource configuration.
  ##
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"

## Default values for Mariadb.
##
mariadb:
  ## Use Mariadb chart dependency
  ## Set to false if using your own Mariadb
  ##
  enabled: true

  ## persistence configuration.
  ##
  persistence:
    enabled: false
    accessMode: "ReadWriteOnce"
    size: "8Gi"

  ## Configuration values for Mariadb.
  ## must match Portus database values.
  ##
  mariadbUser: "portus"
  mariadbDatabase: "portus"
