apiVersion: v1
kind: Service
metadata:
  name: nginx 
spec:
  type: NodePort
  ports:
    - name: portus
      port: 80
      nodePort: 32123
    - name: registry
      port: 443
      nodePort: 32124
  selector:
    name: portus-nginx-apps
